config/routes.rb
Rails.application.routes.draw do
  scope '/admin' do
    root to: 'admin/collectives#index'
    devise_for :users, skip: [:registrations]
    as :user do
      get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
      put 'users', to: 'devise/registrations#update', as: 'user_registration'
      get 'users/extras/edit', to: 'admin/registrations#edit', as: 'admin_edit_user_extras'
    end
    get 'users/registration', to: 'admin/registrations#new', as: 'new_user_registration'
    post 'users/', to: 'admin/registrations#create'
    get 'users/', to: 'admin/registrations#index', as: 'admin_users'
    patch 'users/:id', to: 'admin/registrations#update', as: 'admin_user'
    get 'users/mine', to: 'admin/registrations#show', as: 'admin_user_mine'
    delete 'users/registrations/:id', to: 'admin/registrations#destroy', as: 'destroy_user'
  end
  namespace :admin do
    resources :social_links
    resources :collectives do
      resources :stories
    end
  end
  get '/about', to: 'collectives#about_page', as: 'about_page'
  get '/contact', to: 'collectives#contact_page', as: 'contact_page'
  namespace :api do
    namespace :v1 do
      resources :collectives
      # get 'users/', to: 'registrations#index', as: 'api_users'
      get 'users/:id', to: 'registrations#show', as: 'api_user'
    end
  end
  get 'users/:id', to: 'registrations#show', as: 'show_user'
  get '/', to: 'collectives#home', as: 'index_home'
  resources :collectives
  get 'stories/:id', to: 'stories#show', as: 'story'
  get 'stories/tweet/:id', to: 'stories#tweet', as: 'story_tweet'
  get 'stories/share/:id', to: 'stories#share', as: 'story_share'
  get 'collectives/tweet/:id', to: 'collectives#tweet', as: 'collective_tweet'
  get 'collectives/share/:id', to: 'collectives#share', as: 'collective_share'
  get 'users/tweet/:id', to: 'registrations#tweet', as: 'user_tweet'
  get 'users/share/:id', to: 'registrations#share', as: 'user_share'

  get 'admin/collectives/:id/publish', to: 'admin/collectives#publish', as: 'collective_publish'
  get 'admin/collectives/:id/unpublish', to: 'admin/collectives#unpublish', as: 'collective_unpublish'
end

app/models/collective.rb
class Collective < ActiveRecord::Base
  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_many :stories
  validates :name, length: { minimum: 3, maximum: 26 }, uniqueness: true

  def date_ts
    date.to_time.strftime('%B %d, %Y')
  end

  def shares
    stories.map { |s| s.shares }.reduce(:+)
  end

  def views
    stories.map { |s| s.views }.reduce(:+)
  end
end

app/controllers/admin/collectives_controller.rb
class Admin::CollectivesController < ApplicationController
  before_action :require_login
  load_and_authorize_resource
  def index
    @collectives = Collective.all
  end

  def new
    @collective = Collective.new
  end

  def show
  end

  def create
    Collective.create(collective_params)
    redirect_to '/admin/collectives'
  end

  def edit
  end

  def publish
    @collective.published = true
    @collective.save
    flash[:notice] = "Collective successfully published"
    redirect_to "/admin/collectives/#{params[:id]}"
  end

  def unpublish
    @collective.published = false
    @collective.save
    flash[:notice] = "Collective successfully unpublished"
    redirect_to "/admin/collectives/#{params[:id]}"
  end

  def update
    @collective.update(collective_params)
    flash[:notice] = 'Collective successfully updated'
    redirect_to "/admin/collectives/#{params[:id]}"
  end

  def destroy
    @collective.destroy
    flash[:notice] = 'Collective successfully deleted'
    redirect_to '/admin/collectives'
  end

  private
  def collective_params
    params.require(:collective).permit(:date, :name, :image, :issue_number)
  end

  def require_login
    unless current_user
      redirect_to new_user_session_path
    end
  end
end

app/controllers/api/v1/collectives_controller.rb
module Api
  module V1
    class CollectivesController < ApplicationController
      def index
        @collectives = Collective.all.reverse
      end

      def show
        @collective = Collective.find(params[:id])
      end
    end
  end
end

app/controllers/collectives_controller.rb
class CollectivesController < ApplicationController
  layout "front"
  def index
    @collectives = Collective.order(issue_number: :desc).where(published: true)
  end

  def show
    @collective = Collective.where(id: params[:id], published: true).first
    raise ActionController::RoutingError.new('Not Found') unless @collective 
  end

  def home
    @collectives = Collective.order(issue_number: :desc).where(published: true).first(8)
  end

  def about_page
    render :about
  end

  def contact_page
    render :contact
  end

  def tweet
    collective = Collective.find(params[:id])
    text = "#{collective.name} #{collective_url(collective)}"
    redirect_to "https://twitter.com/intent/tweet?text=#{text}"
  end

  def share
    collective = Collective.find(params[:id])
    referer = "#{collective_url(collective)}"
    redirect_to "http://www.facebook.com/sharer/sharer.php?u=#{referer}"
  end
end

app/helpers/collectives_helper.rb
module CollectivesHelper
end

app/views/collectives/_collectives.html.erb
<div class="collectives">
  <% index = 0 %>
  <% collectives.each do |collective| %>
    <section style="background: url(<%=collective.image%>); background-size:cover;" class="collective ontold-hero">
      <% if index.zero? %>
        <p class="ontold-new-badge"> NEW ISSUE </p>
      <% else %>
        <p class="ontold-badge"> ISSUE <%= collective.issue_number %> </p>
      <% end %>
      <% index+=1 %>
      <p class="ontold-title"> <%= link_to collective.name, collective_path(collective) %></a></p>
      <p class="ontold-date"><%= collective.date_ts %> </p>
    </section>
  <% end %>
</div>

app/views/collectives/about.html.erb
<br><br><br><br>
<section style=" background:url(/img/DSC09553.JPG);box-shadow:inset 0 0 0 1000px rgba(0,0,0,.92); height:1000px;; background-size:cover">
  <h2 class="col-10-fixed reason">
    <p><img src="/assets/img/logo.svg"></p>
    <span style="padding-left:0; font-size:0.9em" class="bandara-lg">Discover the best of African creativity on ontold, curated by a community of creatives with great taste.
    </span>
  </h2>
    <p style="padding-right:1em;" class="col-9-fixed">
      <span class="finds"> We are small community of African creatives curating the best of African content on & off the web. Our community consists of creatives from all fields from photographers to web and software developers to make-up artiste. Read, share and be inspired.
      </span>
    </p>
  <p class="col-9-fixed" style="text-align:left">
  <button id="payges-error-button">
    <span class="ion-social-twitter-outline"></span> Shout us out!</button>
  </p>
</section>

app/views/collectives/contact.html.erb
<br><br><br><br>
<section style=" background:url(img/DSC09553.JPG);box-shadow:inset 0 0 0 1000px rgba(0,0,0,.92); height:1000px;; background-size:cover">
  <h2 class="col-10-fixed reason">
    <p><img src="/assets/img/logop.svg"></p>
    <span style="padding-left:0; font-size:0.9em" class="bandara-lg">We can't wait to hear from you!</span>
  </h2>
  <p style="padding-right:1em;" class="col-9-fixed">
    <span class="finds">
      You can contact us for enquiries or just to say hi by shooting us a mail via
      <span>
        <a class="bandera-link" href="#">hi@ontold.com</a>
      </span> or interact with on on twitter via
      <span><a class="bandera-link" href="#">@theontold</a></span>
      . We will be sure to get back to you as soon as we can!
    </span>
  </section>

app/views/collectives/home.html.erb
<div class="top-mast">
  <section class="payges-black-bg">
    <p class="ontold-hello">
      <span style="margin-top:0.8em;">Ontold is Africa, curated.</span>
      <span style="margin-left:0.4em;">
        <a href="/about">
           <button class="payges-button-sm"> Learn more</button>
        </a>
      </span>
    </p>
  </section>
</div>
<%= render partial: 'collectives', locals: { collectives: @collectives } %>

app/views/collectives/index.html.erb
<br><br><br><br>
<%= render partial: 'collectives', locals: { collectives: @collectives } %>

app/views/collectives/show.html.erb
<br><br>
<section style="background: url(<%= @collective.image.url(:original) %>); background-size:cover;" class="ontold-hero">
	<p class="ontold-badge">
		ISSUE <%= @collective.issue_number %>
	</p>
	<p class="ontold-title"> <a href="#"><%= @collective.name %></a>
	</p>
	<p class="ontold-date"> <%= @collective.date_ts %> &middot;
		<span class="finds"><%= pluralize(@collective.shares, "Share") %></span> &middot;
		<span class="finds"><%= pluralize(@collective.views, "View") %></span>
  </p>
	<p style="text-align:center; margin-top:1em;">
		 <button class="md-trigger payges-button-trans" data-modal="modal-1">
			 Share
			 <span class="mdi-share"></span>
		 </button>
	 </p>
</section>
<%= render partial: '/partials/stories', locals: { stories: @collective.stories } %>

<div class="md-modal md-effect-16" id="modal-1">
	<div  style="text-align:center" class="md-content">
		<p class="folol"> Thanks for sharing!</p>
		<p class="social-sec">
			<a class="mdi-twitter socialsm-white-large"  href="<%= collective_tweet_path(@collective) %>" target="_blank"></a>
			<a class="mdi-facebook socialsm-white-large-last" href="<%= collective_share_path(@collective) %>" target="_blank"></a>
		</p>
		<div>
			<p></p>
			<button style="color:#fff; font-size:1.3em;" class="md-close">
				<span class="ion-ios-close-outline"></span>
			</button>
		</div>
	</div>
</div>