config/routes.rb
Rails.application.routes.draw do
  scope '/admin' do
    root to: 'admin/collectives#index'
    devise_for :users, skip: [:registrations]
    as :user do
      get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
      put 'users', to: 'devise/registrations#update', as: 'user_registration'
      get 'users/extras/edit', to: 'admin/registrations#edit', as: 'admin_edit_user_extras'
    end
    get 'users/registration', to: 'admin/registrations#new', as: 'new_user_registration'
    post 'users/', to: 'admin/registrations#create'
    get 'users/', to: 'admin/registrations#index', as: 'admin_users'
    patch 'users/:id', to: 'admin/registrations#update', as: 'admin_user'
    get 'users/mine', to: 'admin/registrations#show', as: 'admin_user_mine'
    delete 'users/registrations/:id', to: 'admin/registrations#destroy', as: 'destroy_user'
  end
  namespace :admin do
    resources :social_links
    resources :collectives do
      resources :stories
    end
  end
  get '/about', to: 'collectives#about_page', as: 'about_page'
  get '/contact', to: 'collectives#contact_page', as: 'contact_page'
  namespace :api do
    namespace :v1 do
      resources :collectives
      # get 'users/', to: 'registrations#index', as: 'api_users'
      get 'users/:id', to: 'registrations#show', as: 'api_user'
    end
  end
  get 'users/:id', to: 'registrations#show', as: 'show_user'
  get '/', to: 'collectives#home', as: 'index_home'
  resources :collectives
  get 'stories/:id', to: 'stories#show', as: 'story'
  get 'stories/tweet/:id', to: 'stories#tweet', as: 'story_tweet'
  get 'stories/share/:id', to: 'stories#share', as: 'story_share'
  get 'collectives/tweet/:id', to: 'collectives#tweet', as: 'collective_tweet'
  get 'collectives/share/:id', to: 'collectives#share', as: 'collective_share'
  get 'users/tweet/:id', to: 'registrations#tweet', as: 'user_tweet'
  get 'users/share/:id', to: 'registrations#share', as: 'user_share'

  get 'admin/collectives/:id/publish', to: 'admin/collectives#publish', as: 'collective_publish'
  get 'admin/collectives/:id/unpublish', to: 'admin/collectives#unpublish', as: 'collective_unpublish'
end

app/models/collective.rb
class Collective < ActiveRecord::Base
  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_many :stories
  validates :name, length: { minimum: 3, maximum: 26 }, uniqueness: true

  def date_ts
    date.to_time.strftime('%B %d, %Y')
  end

  def shares
    stories.map { |s| s.shares }.reduce(:+)
  end

  def views
    stories.map { |s| s.views }.reduce(:+)
  end
end

app/controllers/admin/collectives_controller.rb
class Admin::CollectivesController < ApplicationController
  before_action :require_login
  load_and_authorize_resource
  def index
    @collectives = Collective.all
  end

  def new
    @collective = Collective.new
  end

  def show
  end

  def create
    Collective.create(collective_params)
    redirect_to '/admin/collectives'
  end

  def edit
  end

  def publish
    @collective.published = true
    @collective.save
    flash[:notice] = "Collective successfully published"
    redirect_to "/admin/collectives/#{params[:id]}"
  end

  def unpublish
    @collective.published = false
    @collective.save
    flash[:notice] = "Collective successfully unpublished"
    redirect_to "/admin/collectives/#{params[:id]}"
  end

  def update
    @collective.update(collective_params)
    flash[:notice] = 'Collective successfully updated'
    redirect_to "/admin/collectives/#{params[:id]}"
  end

  def destroy
    @collective.destroy
    flash[:notice] = 'Collective successfully deleted'
    redirect_to '/admin/collectives'
  end

  private
  def collective_params
    params.require(:collective).permit(:date, :name, :image, :issue_number)
  end

  def require_login
    unless current_user
      redirect_to new_user_session_path
    end
  end
end

app/controllers/api/v1/collectives_controller.rb
module Api
  module V1
    class CollectivesController < ApplicationController
      def index
        @collectives = Collective.all.reverse
      end

      def show
        @collective = Collective.find(params[:id])
      end
    end
  end
end

app/controllers/collectives_controller.rb
class CollectivesController < ApplicationController
  layout "front"
  def index
    @collectives = Collective.order(issue_number: :desc).where(published: true)
  end

  def show
    @collective = Collective.where(id: params[:id], published: true).first
    raise ActionController::RoutingError.new('Not Found') unless @collective 
  end

  def home
    @collectives = Collective.order(issue_number: :desc).where(published: true).first(8)
  end

  def about_page
    render :about
  end

  def contact_page
    render :contact
  end

  def tweet
    collective = Collective.find(params[:id])
    text = "#{collective.name} #{collective_url(collective)}"
    redirect_to "https://twitter.com/intent/tweet?text=#{text}"
  end

  def share
    collective = Collective.find(params[:id])
    referer = "#{collective_url(collective)}"
    redirect_to "http://www.facebook.com/sharer/sharer.php?u=#{referer}"
  end
end

app/helpers/collectives_helper.rb
module CollectivesHelper
end

app/views/admin/collectives/_form.html.erb
<%= form_for [:admin, @collective], html: { multipart: true }  do |f| %>
  <div class="row">
    <div class="six columns">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'u-full-width' %>
    </div>
  </div>
  <div class="row">
    <div class="six columns">
      <%= f.label :issue_number %>
      <%= f.text_field :issue_number, class: 'u-full-width' %>
    </div>
  </div>
  <div class="row">
    <div class="six columns">
      <%= f.label :date %>
      <%= f.date_field :date, class: 'u-full-width' %>
    </div>
  </div>
  <div class="row">
    <div class="six columns">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
</div>
  <%= f.submit %>
<% end %>

app/views/admin/collectives/edit.html.erb
<%= render "form" %>

app/views/admin/collectives/index.html.erb
<div class="row sub-head">
  <h5>Collectives</h5>
  <% if can? :create, @collective %>
    <%= link_to 'Add a collective', new_admin_collective_path, class: "button" %>
  <% end %>
</div>
<% if @collectives.any? %>
  <table class="u-full-width">
    <thead>
      <th>NAME</th>
      <th>ISSUE NUMBER</th>
      <th>DATE</th>    
      <th>ACTIONS</th>
    </thead>
    <tbody>
    <% @collectives.each do |collective| %>
      <tr>
        <td>
          <%= collective.name %>
        </td>
        <td>
          <%= collective.issue_number %>
        </td>
        <td>
          <%= collective.date %>
        </td>
        <td>
          <%= link_to 'View', admin_collective_path(collective), class: "button button-primary action"%>
          <% if can? :update, collective %>
            <%= link_to 'Edit', edit_admin_collective_path(collective), class: "button button-primary orange action" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
<% else %>
  No collectives yet
<% end %>

app/views/admin/collectives/new.html.erb
<%= render "form" %>

app/views/admin/collectives/show.html.erb
<h5><strong>TITLE: &nbsp;&nbsp;</strong><%= @collective.name %></h5>
<h6><strong>ISSUE NUMBER: &nbsp;&nbsp;</strong><%= @collective.issue_number %></h6>
<h6><strong>DATE: &nbsp;&nbsp;</strong><%= @collective.date %></h6>
<% if can? :update, @collective %>
  <%= link_to 'Edit', edit_admin_collective_path(@collective), class: "button action" %>
  <% if @collective.published %>
    <%= link_to "unpublish", collective_unpublish_path(@collective), class: "button action" %>
  <% else %>
    <%= link_to "publish", collective_publish_path(@collective), class: "button action" %>
  <% end %>
<% end %>
<% if can? :destroy, @collective %>
  <%= link_to 'Delete', admin_collective_path(@collective), method: :delete, class: "button action"%>
<% end %>
<br>
<br>
<div class="row sub-head">
  <h5>Stories</h5>
    <%= link_to 'Add Story', new_admin_collective_story_path(@collective), class: "button" %>
</div>
<table class="u-full-width">
  <thead>
    <th>NAME</th>
    <th>ACTIONS</th>
  </thead>
  <tbody>
    <% @collective.stories.each do |story| %>
    <tr>
      <td>
        <%= story.title %>
      </td>
      <td class="actions">
        <%= link_to "View", admin_collective_story_path(@collective, story), class: "button button-primary action" %>
        <% if can? :update, story %>
          <%= link_to "Edit", edit_admin_collective_story_path(@collective, story), class: "button button-primary orange action" %>
        <% end %>
        <% if can? :destroy, story %>
          <%= link_to "Delete", admin_collective_story_path(@collective, story), method: :delete, class: "button button-primary red action" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>