config/routes.rb
Rails.application.routes.draw do
  scope '/admin' do
    root to: 'admin/collectives#index'
    devise_for :users, skip: [:registrations]
    as :user do
      get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
      put 'users', to: 'devise/registrations#update', as: 'user_registration'
      get 'users/extras/edit', to: 'admin/registrations#edit', as: 'admin_edit_user_extras'
    end
    get 'users/registration', to: 'admin/registrations#new', as: 'new_user_registration'
    post 'users/', to: 'admin/registrations#create'
    get 'users/', to: 'admin/registrations#index', as: 'admin_users'
    patch 'users/:id', to: 'admin/registrations#update', as: 'admin_user'
    get 'users/mine', to: 'admin/registrations#show', as: 'admin_user_mine'
    delete 'users/registrations/:id', to: 'admin/registrations#destroy', as: 'destroy_user'
  end
  namespace :admin do
    resources :social_links
    resources :collectives do
      resources :stories
    end
  end
  get '/about', to: 'collectives#about_page', as: 'about_page'
  get '/contact', to: 'collectives#contact_page', as: 'contact_page'
  namespace :api do
    namespace :v1 do
      resources :collectives
      # get 'users/', to: 'registrations#index', as: 'api_users'
      get 'users/:id', to: 'registrations#show', as: 'api_user'
    end
  end
  get 'users/:id', to: 'registrations#show', as: 'show_user'
  get '/', to: 'collectives#home', as: 'index_home'
  resources :collectives
  get 'stories/:id', to: 'stories#show', as: 'story'
  get 'stories/tweet/:id', to: 'stories#tweet', as: 'story_tweet'
  get 'stories/share/:id', to: 'stories#share', as: 'story_share'
  get 'collectives/tweet/:id', to: 'collectives#tweet', as: 'collective_tweet'
  get 'collectives/share/:id', to: 'collectives#share', as: 'collective_share'
  get 'users/tweet/:id', to: 'registrations#tweet', as: 'user_tweet'
  get 'users/share/:id', to: 'registrations#share', as: 'user_share'

  get 'admin/collectives/:id/publish', to: 'admin/collectives#publish', as: 'collective_publish'
  get 'admin/collectives/:id/unpublish', to: 'admin/collectives#unpublish', as: 'collective_unpublish'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ontold Admin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
      <div class="container">
        <ul class="navbar-list row">
          <a href="/admin/collectives"><img class='logo-dash' src="/img/logo-dash.png" alt="logo" /></a>
          <% if user_signed_in? %>
            <li class="navbar-item two columns">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-link" %>
            </li>
            <li class="navbar-item two columns">
                <%= link_to "Account", admin_user_mine_path, class: "navbar-link" %>
            </li>
            <% if can? :create, User %>
            <li class="navbar-item two columns">
                <%= link_to "Users", admin_users_path, class: "navbar-link" %>
            </li>
            <% end %>
            <li class="navbar-item two columns">
              <%= link_to "Collectives", admin_collectives_path, class: "navbar-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title> Ontold | Africa, Curated. </title>
    <link rel="shortcut icon" href="/assets/img/favicon.png">
    <link rel="stylesheet" type="text/css" href="/assets/css/style.css" />
    <link rel="stylesheet" type="text/css" href="/assets/fonts/Bandera.css" />
    <link rel="stylesheet" type="text/css" href="/assets/fonts/MaterialDesign-Webfont-master/css/materialdesignicons.css" />
    <link rel="stylesheet" type="text/css" href="/assets/fonts/ionicons-2.0.1/ionicons-2.0.1/css/ionicons.css" />
    <link rel="stylesheet" type="text/css" href="/assets/fonts/fonts.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/custom.css" />
    <script src="/assets/js/modernizr.custom.js"></script>
    <script src="/assets/js/modernizr.min.js"></script>
    <script src="/assets/js/modernizr.js"></script>
  </head>
  <body class="fade-in one">
    <header class="cd-header">
        <div id="cd-logo">
          <a href="/"><img style="width:150px;" src="/assets/img/cd-logo.svg" alt="Logo"></a>
        </div>
        <nav class="cd-main-nav">
        		<ul>
        			<li>
                <%= link_to 'Home', index_home_path %>
              </li>
        			<li>
                <%= link_to 'Collectives', collectives_path %>
              </li>
              <li>
                <%= link_to 'About', about_page_path %>
              </li>
              <li>
                <%= link_to 'Contact', contact_page_path %>
              </li>
          	</ul>
        </nav>
    </header>
    <%= yield %>
    <% unless (current_page?('/about') || current_page?('/contact')) %>
    <section class="payges-white-bg">
      <p class="payges-hello">There's more where that came from.</p>
      <p class="payges-hello-sm">Discover the best of African content on Ontold, curated by our tastemakers.</p>
      <button style="text-align:center;" class="payges-button"> <%= link_to 'SEE ALL EDITIONS ', collectives_path %> <span class="ion-android-arrow-forward"></span></button>
      <p class="folol"> follow the wave</p>
      <p class="social-sec">
        <a class="mdi-twitter socialsm" href="#"></a>
        <a class="mdi-facebook socialsm"href="#"></a>
        <a class="mdi-tumblr socialsm" href="#"></a>
        <a class="mdi-pinterest socialsm"href="#"></a>
        <a class="ion-social-instagram socialsm-last" href="#"></a>
      </p>
    </section>
    <% end %>
    <div class="md-overlay"></div>
    <script src="/assets/js/classie.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/assets/js/main.js"></script>
    <script src="/assets/js/modalEffects.js"></script>
  </body>
</html>